# Generated by Django 5.2.17 on 2026-08-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciafotografica',
            name='imagen_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL o Data Base64 de Imagen'),
        ),
    ]
