# Generated by Django 5.2.17 on 2026-08-12 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_evidenciafotografica_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('unidad_defecto', models.CharField(default='unidades', max_length=30)),
                ('stock_disponible', models.PositiveIntegerField(default=100)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoriamaterial')),
            ],
            options={
                'verbose_name': 'Material de Pañol',
                'verbose_name_plural': 'Materiales de Pañol',
                'ordering': ['nombre'],
            },
        ),
    ]
