# Generated by Django 5.2.17 on 2026-08-13 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('observacion_gestor', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inasistencia',
                'verbose_name_plural': 'Inasistencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
