# Generated by Django 5.2.17 on 2026-08-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiontrabajo',
            name='es_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesiontrabajo',
            name='tipo',
            field=models.CharField(choices=[('avance', 'Avance Diario'), ('final', 'Informe Final de Reparación')], default='avance', max_length=20),
        ),
    ]
