# Generated by Django 5.2.17 on 2026-08-17 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sesiontrabajo_es_final_sesiontrabajo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciafotografica',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='api.sesiontrabajo'),
        ),
        migrations.AddField(
            model_name='materialutilizado',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='api.sesiontrabajo'),
        ),
    ]
