# Generated by Django 5.2.17 on 2026-08-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_evidenciafotografica_sesion_materialutilizado_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subestado_rechazo',
            field=models.CharField(blank=True, choices=[('falsa_alarma', 'Falsa Alarma / Incidente Inválido'), ('requiere_proveedor_externo', 'Requiere Cotización / Empresa Externa'), ('duplicado', 'Ticket Duplicado'), ('otro', 'Otro Motivo')], max_length=40, null=True, verbose_name='Sub-estado de Rechazo / Inviabilidad'),
        ),
    ]
