# Generated by Django 5.2.17 on 2026-08-30 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ticket_guardia_asignado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesiontrabajo',
            options={'ordering': ['inicio'], 'verbose_name': 'Sesión de Trabajo', 'verbose_name_plural': 'Sesiones de Trabajo'},
        ),
    ]
